### ISSUE TITLE
Make Blavity Daily newsletter Working 

### ISSUE THREAD

**Issue by ldeveloper7** [ldeveloper7/vue-start#20]
**API**  
_https://api.blavity.com/v1/subscribe_

**Params :-** 

1. **token**
2. `"user": {"email":"meghna@blavity.com","name":"unknown"}`

**Comment by mayurkapadia35** [comment]
Completed from my side, made a new branch from develop called newsletter
this is a PR for that https://github.com/ldeveloper7/vue-start/pull/25
But one issue is there, that it returns a internal server error from backend.
